title: IXOLIST Marketing
email:
description: IXOLIST Marketing website
baseurl: ""
url: ""
github_username:  Saifas Jekyll

# Build settings
plugins:
  - jekyll-feed

contents_root_path: /contents/
contents_pages_path: /contents/pages/

source: ./

destination: ../app-build-static

layouts_dir: ./templates/_layouts/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/